language: node_js
node_js:
  - node
  - 6
  - 4
env:
  - CXX=g++-4.8
sudo: required
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
    npm install -g grunt-cli